import turtle
tortuga = turtle.Pen()
tortuga.color('blue')
tortuga.forward(100)
tortuga.color('red')
tortuga.left(90)
tortuga.forward(100)
tortuga.color('blue')
tortuga.left(90)
tortuga.forward(100)
tortuga.color('red')
tortuga.left(90)
tortuga.forward(100)
tortuga.color('green')
tortuga.left(135)
tortuga.forward(140)
input()
